# fly.toml app configuration file generated for x-payments-api on 2023-10-31T13:48:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "x-payments-api"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
